import type { Category, Product } from "./types"

export const categories: Category[] = [
  {
    id: "metale",
    name: "Metale",
    slug: "metale",
    description: "Oțel beton și fier beton fasonat pentru construcții",
    productCount: 15,
    subcategories: [
      { id: "fier-beton", name: "Fier Beton", slug: "fier-beton" },
      { id: "fier-beton-fasonat", name: "Fier Beton Fasonat", slug: "fier-beton-fasonat" },
    ],
  },
  {
    id: "zidarie",
    name: "Zidărie",
    slug: "zidarie",
    description: "BCA și cărămizi pentru construcții",
    productCount: 28,
    subcategories: [
      { id: "bca", name: "BCA", slug: "bca" },
      { id: "caramida", name: "Cărămidă", slug: "caramida" },
    ],
  },
  {
    id: "lianti",
    name: "Lianți",
    slug: "lianti",
    description: "Amorse, ciment, gleturi și mortare",
    productCount: 45,
    subcategories: [
      { id: "amorse", name: "Amorse", slug: "amorse" },
      { id: "ciment", name: "Ciment", slug: "ciment" },
      { id: "gleturi", name: "Gleturi", slug: "gleturi" },
      { id: "mortare", name: "Mortare", slug: "mortare" },
    ],
  },
  {
    id: "izolarii",
    name: "Izolații",
    slug: "izolarii",
    description: "Materiale pentru hidroizolații",
    productCount: 8,
    subcategories: [{ id: "hidroizolarii", name: "Hidroizolații", slug: "hidroizolarii" }],
  },
  {
    id: "adezivi",
    name: "Adezivi",
    slug: "adezivi",
    description: "Adezivi pentru diverse aplicații în construcții",
    productCount: 32,
    subcategories: [
      { id: "adezivi-gips-carton", name: "Adezivi Gips Carton", slug: "adezivi-gips-carton" },
      { id: "adezivi-gresie-faianta", name: "Adezivi Gresie și Faianță", slug: "adezivi-gresie-faianta" },
      { id: "adezivi-polistiren", name: "Adezivi Polistiren", slug: "adezivi-polistiren" },
      { id: "adezivi-vata-minerala", name: "Adezivi Vată Minerală", slug: "adezivi-vata-minerala" },
      { id: "adezivi-zidarie", name: "Adezivi Zidărie", slug: "adezivi-zidarie" },
    ],
  },
  {
    id: "gips-carton",
    name: "Gips Carton",
    slug: "gips-carton",
    description: "Plăci, profile și accesorii pentru gips carton",
    productCount: 55,
    subcategories: [
      { id: "placi-gips-carton", name: "Plăci Gips Carton", slug: "placi-gips-carton" },
      { id: "accesorii-gips-carton", name: "Accesorii Gips Carton", slug: "accesorii-gips-carton" },
      { id: "profile-gips-carton", name: "Profile Gips Carton", slug: "profile-gips-carton" },
    ],
  },
  {
    id: "tego",
    name: "TEGO",
    slug: "tego",
    description: "Panouri TEGO pentru cofraje",
    productCount: 3,
    subcategories: [{ id: "panouri-tego", name: "Panouri TEGO", slug: "panouri-tego" }],
  },
  {
    id: "tencuieli-decorative",
    name: "Tencuieli Decorative",
    slug: "tencuieli-decorative",
    description: "Tencuieli decorative pentru finisaje",
    productCount: 6,
    subcategories: [{ id: "tencuieli-decorative", name: "Tencuieli Decorative", slug: "tencuieli-decorative" }],
  },
  {
    id: "produse-sika",
    name: "Produse Sika",
    slug: "produse-sika",
    description: "Materiale de finisare și sigilări Sika",
    productCount: 18,
    subcategories: [
      { id: "materiale-finisare", name: "Materiale Finisare", slug: "materiale-finisare" },
      { id: "sigilari-lipiri", name: "Sigilări și Lipiri", slug: "sigilari-lipiri" },
    ],
  },
]

export const products: Product[] = [
  // METALE - Fier Beton
  {
    id: "1",
    name: "Otel beton OB37 Ф6, colac",
    slug: "otel-beton-ob37-6-colac",
    description: "Oțel beton OB37 cu diametrul de 6mm, livrat în colac. Ideal pentru armarea betoanelor.",
    price: 4.5,
    unit: "kg",
    categoryId: "metale",
    subcategoryId: "fier-beton",
    images: ["/placeholder.svg?height=400&width=400"],
    inStock: true,
    rating: 4.5,
    reviews: 23,
    badge: "Bestseller",
    specifications: {
      Diametru: "6mm",
      Tip: "OB37",
      Forma: "Colac",
      "Greutate colac": "~50kg",
      Standard: "SR EN 10080",
    },
  },
  {
    id: "2",
    name: "Otel beton OB37 Ф8, colac",
    slug: "otel-beton-ob37-8-colac",
    description: "Oțel beton OB37 cu diametrul de 8mm, livrat în colac.",
    price: 4.45,
    unit: "kg",
    categoryId: "metale",
    subcategoryId: "fier-beton",
    images: ["/placeholder.svg?height=400&width=400"],
    inStock: true,
    rating: 4.6,
    reviews: 31,
    specifications: {
      Diametru: "8mm",
      Tip: "OB37",
      Forma: "Colac",
      "Greutate colac": "~50kg",
      Standard: "SR EN 10080",
    },
  },
  {
    id: "3",
    name: "Otel beton BST500C Ф8, bara",
    slug: "otel-beton-bst500c-8-bara",
    description: "Oțel beton BST500C cu diametrul de 8mm, livrat în bare de 12m.",
    price: 4.8,
    unit: "kg",
    categoryId: "metale",
    subcategoryId: "fier-beton",
    images: ["/placeholder.svg?height=400&width=400"],
    inStock: true,
    rating: 4.7,
    reviews: 45,
    specifications: {
      Diametru: "8mm",
      Tip: "BST500C",
      Forma: "Bara",
      Lungime: "12m",
      Standard: "SR EN 10080",
    },
  },
  {
    id: "4",
    name: "Otel beton BST500C Ф10, bara",
    slug: "otel-beton-bst500c-10-bara",
    description: "Oțel beton BST500C cu diametrul de 10mm, livrat în bare de 12m.",
    price: 4.75,
    unit: "kg",
    categoryId: "metale",
    subcategoryId: "fier-beton",
    images: ["/placeholder.svg?height=400&width=400"],
    inStock: true,
    rating: 4.8,
    reviews: 52,
    specifications: {
      Diametru: "10mm",
      Tip: "BST500C",
      Forma: "Bara",
      Lungime: "12m",
      Standard: "SR EN 10080",
    },
  },
  {
    id: "5",
    name: "Otel beton BST500C Ф12, bara",
    slug: "otel-beton-bst500c-12-bara",
    description: "Oțel beton BST500C cu diametrul de 12mm, livrat în bare de 12m.",
    price: 4.7,
    unit: "kg",
    categoryId: "metale",
    subcategoryId: "fier-beton",
    images: ["/placeholder.svg?height=400&width=400"],
    inStock: true,
    rating: 4.9,
    reviews: 67,
    badge: "Bestseller",
    specifications: {
      Diametru: "12mm",
      Tip: "BST500C",
      Forma: "Bara",
      Lungime: "12m",
      Standard: "SR EN 10080",
    },
  },

  // METALE - Fier Beton Fasonat
  {
    id: "6",
    name: "Otel beton fasonat BST500C Ф8",
    slug: "otel-beton-fasonat-bst500c-8",
    description: "Oțel beton fasonat BST500C cu diametrul de 8mm, prelucrat conform specificațiilor.",
    price: null,
    unit: "kg",
    categoryId: "metale",
    subcategoryId: "fier-beton-fasonat",
    images: ["/placeholder.svg?height=400&width=400"],
    inStock: true,
    rating: 4.4,
    reviews: 18,
    specifications: {
      Diametru: "8mm",
      Tip: "BST500C",
      Forma: "Fasonat",
      Prelucrare: "La comandă",
      Standard: "SR EN 10080",
    },
  },
  {
    id: "7",
    name: "Otel beton fasonat BST500C Ф10",
    slug: "otel-beton-fasonat-bst500c-10",
    description: "Oțel beton fasonat BST500C cu diametrul de 10mm, prelucrat conform specificațiilor.",
    price: null,
    unit: "kg",
    categoryId: "metale",
    subcategoryId: "fier-beton-fasonat",
    images: ["/placeholder.svg?height=400&width=400"],
    inStock: true,
    rating: 4.5,
    reviews: 22,
    specifications: {
      Diametru: "10mm",
      Tip: "BST500C",
      Forma: "Fasonat",
      Prelucrare: "La comandă",
      Standard: "SR EN 10080",
    },
  },

  // ZIDĂRIE - BCA
  {
    id: "8",
    name: "BCA Ytong 599x50x199mm",
    slug: "bca-ytong-599x50x199mm",
    description: "Bloc din beton celular autoclavizat Ytong, dimensiuni 599x50x199mm.",
    price: 3.2,
    unit: "buc",
    categoryId: "zidarie",
    subcategoryId: "bca",
    images: ["/placeholder.svg?height=400&width=400"],
    inStock: true,
    rating: 4.7,
    reviews: 89,
    badge: "Bestseller",
    specifications: {
      Dimensiuni: "599x50x199mm",
      Marca: "Ytong",
      Densitate: "400 kg/m³",
      "Conductivitate termică": "0.10 W/mK",
      "Rezistență la compresiune": "3.5 N/mm²",
    },
  },
  {
    id: "9",
    name: "BCA Ytong 599x100x199mm",
    slug: "bca-ytong-599x100x199mm",
    description: "Bloc din beton celular autoclavizat Ytong, dimensiuni 599x100x199mm.",
    price: 6.4,
    unit: "buc",
    categoryId: "zidarie",
    subcategoryId: "bca",
    images: ["/placeholder.svg?height=400&width=400"],
    inStock: true,
    rating: 4.8,
    reviews: 156,
    badge: "Bestseller",
    specifications: {
      Dimensiuni: "599x100x199mm",
      Marca: "Ytong",
      Densitate: "400 kg/m³",
      "Conductivitate termică": "0.10 W/mK",
      "Rezistență la compresiune": "3.5 N/mm²",
    },
  },

  // ZIDĂRIE - Cărămidă
  {
    id: "10",
    name: "Caramida Porotherm 30 STh, 250x300x238mm",
    slug: "caramida-porotherm-30-sth",
    description: "Cărămidă Porotherm 30 STh cu proprietăți termice îmbunătățite.",
    price: 4.85,
    unit: "buc",
    categoryId: "zidarie",
    subcategoryId: "caramida",
    images: ["/placeholder.svg?height=400&width=400"],
    inStock: true,
    rating: 4.6,
    reviews: 73,
    specifications: {
      Dimensiuni: "250x300x238mm",
      Marca: "Porotherm",
      Tip: "30 STh",
      "Conductivitate termică": "0.18 W/mK",
      "Rezistență la compresiune": "10 N/mm²",
    },
  },

  // LIANȚI - Amorse
  {
    id: "11",
    name: "Amorsa perete interior/exterior Ceresit CT 17 10L",
    slug: "amorsa-ceresit-ct17-10l",
    description: "Amorsă concentrată pentru pereți interiori și exteriori Ceresit CT 17.",
    price: 45.9,
    unit: "buc",
    categoryId: "lianti",
    subcategoryId: "amorse",
    images: ["/placeholder.svg?height=400&width=400"],
    inStock: true,
    rating: 4.7,
    reviews: 124,
    badge: "Bestseller",
    specifications: {
      Volum: "10L",
      Marca: "Ceresit",
      Tip: "CT 17",
      Aplicare: "Interior/Exterior",
      Randament: "50-100 ml/m²",
    },
  },

  // LIANȚI - Ciment
  {
    id: "12",
    name: "Ciment Romcim Ultra 40kg",
    slug: "ciment-romcim-ultra-40kg",
    description: "Ciment Portland compozit CEM II/A-LL 42,5R Romcim Ultra.",
    price: 28.5,
    unit: "sac",
    categoryId: "lianti",
    subcategoryId: "ciment",
    images: ["/placeholder.svg?height=400&width=400"],
    inStock: true,
    rating: 4.8,
    reviews: 267,
    badge: "Bestseller",
    specifications: {
      Greutate: "40kg",
      Marca: "Romcim",
      Tip: "CEM II/A-LL 42,5R",
      Clasa: "42.5R",
      Standard: "SR EN 197-1",
    },
  },

  // LIANȚI - Gleturi
  {
    id: "13",
    name: "Glet pentru interior Ceresit CT 126 20kg",
    slug: "glet-ceresit-ct126-20kg",
    description: "Glet pe bază de ipsos pentru finisarea pereților interiori.",
    price: 32.4,
    unit: "sac",
    categoryId: "lianti",
    subcategoryId: "gleturi",
    images: ["/placeholder.svg?height=400&width=400"],
    inStock: true,
    rating: 4.6,
    reviews: 98,
    specifications: {
      Greutate: "20kg",
      Marca: "Ceresit",
      Tip: "CT 126",
      Baza: "Ipsos",
      "Grosime strat": "1-5mm",
    },
  },

  // ADEZIVI - Gresie și Faianță
  {
    id: "14",
    name: "Adeziv gresie si faianta Ceresit CM 11 Plus 25kg",
    slug: "adeziv-ceresit-cm11-plus-25kg",
    description: "Adeziv pentru gresie și faianță Ceresit CM 11 Plus, interior și exterior.",
    price: 42.8,
    unit: "sac",
    categoryId: "adezivi",
    subcategoryId: "adezivi-gresie-faianta",
    images: ["/placeholder.svg?height=400&width=400"],
    inStock: true,
    rating: 4.9,
    reviews: 189,
    badge: "Bestseller",
    specifications: {
      Greutate: "25kg",
      Marca: "Ceresit",
      Tip: "CM 11 Plus",
      Aplicare: "Interior/Exterior",
      "Timp deschis": "20 min",
    },
  },

  // GIPS CARTON - Plăci
  {
    id: "15",
    name: "Gips carton Rigips RB 12,5, 1200x2000mm",
    slug: "gips-carton-rigips-rb-125-1200x2000",
    description: "Placă de gips carton standard Rigips RB 12,5mm.",
    price: 28.9,
    unit: "buc",
    categoryId: "gips-carton",
    subcategoryId: "placi-gips-carton",
    images: ["/placeholder.svg?height=400&width=400"],
    inStock: true,
    rating: 4.7,
    reviews: 234,
    badge: "Bestseller",
    specifications: {
      Dimensiuni: "1200x2000mm",
      Grosime: "12.5mm",
      Marca: "Rigips",
      Tip: "RB (Standard)",
      Greutate: "~24 kg",
    },
  },

  // TEGO
  {
    id: "16",
    name: "Panou Tego 21mm, 1250x2500mm",
    slug: "panou-tego-21mm-1250x2500",
    description: "Panou TEGO pentru cofraje, grosime 21mm.",
    price: 89.5,
    unit: "buc",
    categoryId: "tego",
    subcategoryId: "panouri-tego",
    images: ["/placeholder.svg?height=400&width=400"],
    inStock: true,
    rating: 4.5,
    reviews: 45,
    specifications: {
      Dimensiuni: "1250x2500mm",
      Grosime: "21mm",
      Material: "Placaj rezistent",
      Utilizări: "~50 cicluri",
      Greutate: "~65 kg",
    },
  },

  // TENCUIELI DECORATIVE
  {
    id: "17",
    name: "Tencuiala decorativa siliconica Ceresit CT 75",
    slug: "tencuiala-decorativa-ceresit-ct75",
    description: "Tencuială decorativă siliconică Ceresit CT 75 pentru exterior.",
    price: 89.9,
    unit: "galeata",
    categoryId: "tencuieli-decorative",
    subcategoryId: "tencuieli-decorative",
    images: ["/placeholder.svg?height=400&width=400"],
    inStock: true,
    rating: 4.8,
    reviews: 67,
    badge: "Premium",
    specifications: {
      Volum: "25kg",
      Marca: "Ceresit",
      Tip: "CT 75",
      Baza: "Siliconică",
      Granulație: "1.5mm",
    },
  },

  // PRODUSE SIKA - Materiale Finisare
  {
    id: "18",
    name: "SikaHome® TileBond Ceramic Adeziv pentru placari ceramice",
    slug: "sikahome-tilebond-ceramic",
    description: "Adeziv pentru plăcări ceramice SikaHome TileBond Ceramic.",
    price: 38.9,
    unit: "sac",
    categoryId: "produse-sika",
    subcategoryId: "materiale-finisare",
    images: ["/placeholder.svg?height=400&width=400"],
    inStock: true,
    rating: 4.6,
    reviews: 34,
    specifications: {
      Greutate: "25kg",
      Marca: "Sika",
      Tip: "TileBond Ceramic",
      Aplicare: "Interior",
      "Timp deschis": "15 min",
    },
  },

  // PRODUSE SIKA - Sigilări și Lipiri
  {
    id: "19",
    name: "Sikaflex -11 FC+ Gri 300ml Adeziv si sigilant poliuretanic",
    slug: "sikaflex-11-fc-plus-gri-300ml",
    description: "Adeziv și sigilant poliuretanic Sikaflex-11 FC+ pentru multiple aplicații.",
    price: 24.9,
    unit: "buc",
    categoryId: "produse-sika",
    subcategoryId: "sigilari-lipiri",
    images: ["/placeholder.svg?height=400&width=400"],
    inStock: true,
    rating: 4.9,
    reviews: 156,
    badge: "Premium",
    specifications: {
      Volum: "300ml",
      Marca: "Sika",
      Tip: "Sikaflex-11 FC+",
      Culoare: "Gri",
      Baza: "Poliuretanică",
    },
  },

  // Additional products to reach a good variety
  {
    id: "20",
    name: "BCA Izopor Elpreco 650x125x200mm",
    slug: "bca-izopor-elpreco-650x125x200",
    description: "Bloc din beton celular autoclavizat Izopor Elpreco.",
    price: 7.8,
    unit: "buc",
    categoryId: "zidarie",
    subcategoryId: "bca",
    images: ["/placeholder.svg?height=400&width=400"],
    inStock: true,
    rating: 4.5,
    reviews: 67,
    specifications: {
      Dimensiuni: "650x125x200mm",
      Marca: "Elpreco",
      Densitate: "400 kg/m³",
      "Conductivitate termică": "0.10 W/mK",
    },
  },
]
